---
- name: Configure server(s)
  hosts: testServer
  remote_user: vagrant
#  gather_facts: False
  become: True
  
  vars:
    ansible_ssh_private_key_file: "id_rsa"
  
  roles:
    - apt-update
    - pip
    - docker
    - overlay_network
    - neo4j
#    - jenkins
#    - skills_matrix
- name: Configure jar server
  hosts: jarserver
  remote_user: vagrant
  become: True

  vars:
    ansible_ssh_private_key_file: "id_rsa"

  roles:
    - apt-update
    - pip
    - docker
#    - overlay_network
    - skills_matrix
