- name: Run Neo4j Database
  become: true
  docker_container:
    name: neo4j
    image: neo4j
    privileged: yes
    keep_volumes: yes
    state: started
    memory: 1000M
    #recreate: yes
    pull: true
    published_ports:
      - "7687:7687"
      - "7473:7473"
      - "7474:7474"
    volumes:
      - "/tmp/neo4j/data:/data"
      - "/tmp/neo4j/logs:/logs"
    purge_networks: yes
    restart_policy: always
    restart: yes
    working_dir: /tmp/neo4j/
    

- name: Connect to attachable-overlay network
  become: true
  shell: sudo docker network connect skills_overlay neo4j

#      - "7473:7473"
 #   env: 
#      - "NEO4J_AUTH:none"
#    links:
#      - "Skills_Matrix"
#    command: "docker run --publish=7473:7473 --publish=7687:7687"
