- name: Run Skills Matrix
  docker_container:
    name: Skills_Matrix
    image: michaelmernin/skills_matrix_test_perf
    state: started
    pull: true
    ports:
      - "8080:8080"
    purge_networks: yes
    restart: yes
    networks:
      name: talking
      aliases:
        - api
    volumes_from: db
#    links:
#      - "neo4j"
