#- name: run skills with shell command
 # become: true
  #shell: sudo docker run --rm -p 8080:8080 --network="attachable-overlay" michaelmernin/skills_matrix_test_perf:open

- name: Run Skills Matrix
  become: true
  docker_container:
    name: skills_matrix
    image: michaelmernin/skills_matrix_test_perf:open
    state: started
    privileged: true
    pull: true
    ports:
      - "111.1.1.2:8080:8080"
      #- "111.1.1.2:8080:8080/udp"

#    networks:
 #     - name: skills_overlay
  #      links:
   #       - neo4j
#    volumes_from:
 #     - neo4j
    #links:
     # - "/neo4j"
    purge_networks: yes
    restart: yes
    #networks:
    #  - name: skills_overlay
      #aliases:
       # - api
#    volumes_from: db
#    links:
#      - "neo4j"
- name: Connect to skills_overlay network
  become: true
  shell: sudo docker network connect skills_overlay skills_matrix
