- name: Join Swarm Network
  become: true
  docker_swarm:
    state: join
    listen_addr: 222.2.2.2:2377
    advertise_addr: 111.1.1.2
    join_token: SWMTKN-1-2rqdvknraib61s7su6wh4duk2ctn1rnjd6aoukqczfejz5km2r-a0osxhzo7u846uykq7sh88m5x 
    remote_addrs: [ '222.2.2.2:2377' ]
