- name: Instantiate Docker Swarm Node
  become: true
#  shell: docker swarm init --advertise-addr 222.2.2.2
  docker_swarm:
    state: present
    advertise_addr: 222.2.2.2

#- name: Leave swarm for a node
#  docker_swarm:
#    state: absent 
    
- name: Create Overlay Network --Talking--
  become: true
  docker_network:
    name: talking
    driver: overlay
    #attachable: true
    appends: yes
    tls_hostname: 222.2.2.2
    connected:
      - neo4j
      - skills_matrix
  
  
